---
title: "Binary Logistic Regression"
author: "Anna Talken"
date: "2/7/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(GGally)
library(broom)
library(jtools)
```

## Read in the data
```{r}
palmetto <- read_csv(here("data", "palmetto.csv"),
                     col_types = cols(.default = 'c')) %>% 
  mutate(height = as.numeric(height)) %>% 
  mutate(width = as.numeric(width)) %>% 
  mutate(length = as.numeric(length)) %>% 
  mutate(green_lvs = as.numeric(green_lvs)) %>% 
    select(species, height, length, width, green_lvs)
```

## Data visualization exploring differences in height, canopy length, canopy width, and green leaves for two species

```{r, fig.cap = "Figure 1. Exploratory scatterplot comparing canopy hieght and canopy width in Florida Palmettos between two species. Red= Species 1, Blue = species 2."}
  ggplot(data = palmetto, aes(x = width, y = height, color = species)) +
  geom_point(na.rm = TRUE, alpha = 1/2) 
```
```{r, fig.cap = Figure 2. Second exploratory graph comparing the density of green leaves between species}
# Second exploratory graph
ggplot(data = palmetto, aes(x = green_lvs, group = species, fill = species)) +
  geom_density(adjust = 1.5)
```
```{r}
ggplot(data = palmetto, aes(x = green_lvs, y = length, color = species, shape = species)) +
  geom_point() +
  scale_color_brewer() +
  theme_minimal()
```



## Binary logistic regression

## how successful this model would classify a plant correctly
